In [1]:
import pandas as pd
import numpy as np
from numpy import array
from sklearn.preprocessing import MinMaxScaler
import json

from keras.layers import LSTM 
from keras.models import Sequential 
from keras.layers import Dense 
import keras.backend as K 
from keras.callbacks import EarlyStopping

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
injectedDatas = [34.83224236908429, 38.394367588276275, 37.579518238484624, 37.74300693749113, 38.06369325008627, 39.136891050081, 38.83935291033777, 39.01797017572035, 39.68045150525125, 40.204058176569795, 39.84501139969038, 39.244480069107084, 40.3761361923844, 40.26156890699409, 40.153725019442604, 39.391420418809794, 39.33346505386614, 39.88922204294403, 41.076768707483, 
41.358794328170625, 41.445837865904814, 40.51715463489579, 41.060407805305104, 41.51888979845368, 42.288169825612535, 41.3909046254621, 42.715149643790326, 42.20794823829377, 41.79490309813209, 43.16616981286145, 43.81834096354773, 44.97969216961809, 44.09879314353525, 43.508285321806405, 43.43420019935673, 45.05903397214512, 46.427791104367195, 47.7097430955803, 48.0181417490547, 46.40524519369148, 45.89569833519653, 47.70825228252702, 46.58339470802992, 48.08678838844567, 47.084919122151085, 46.54260851695099, 47.01443941547207, 48.69176006596454, 49.810953720642225, 51.55588533599991, 50.97731798939761, 50.51571570389831, 50.32431864283693, 52.5421205725567, 52.75660175714154, 53.73337437170944, 53.7063915407251, 
52.789383283500634, 52.30689444461551, 52.640197266042726, 54.23013395115101, 54.388868585525806, 53.08033301253741, 51.6675316444387, 52.486662965585836, 53.14765439990886, 54.1587136523392, 54.77485494446756, 56.03110021157096, 54.893770856024716, 54.45035517154836, 56.14507842390942, 55.792199639394894, 55.99342456510048, 55.583408872003616, 55.84786841367523, 55.47163493136508, 56.57146224839659, 57.10096673400386, 57.12768434401999, 57.250159949051806, 55.90118743345152, 56.34905453614046, 55.084281394385854, 57.03054279413578, 57.363634493874955, 57.01660559434598, 56.716075049988746, 56.72788198068005, 56.266388095553545, 58.14312710799354, 57.71086008659689, 58.399685143195796, 57.619495982689806, 56.42044651349554, 57.63721375976017, 58.44710490975076, 59.17784861220598, 57.73857898958503, 57.125582438732486, 57.233896823256615, 58.171856866345905, 57.51298970407039, 57.6193893537885, 58.41081643977983, 57.47890227062343, 57.911347998967244, 59.2113151088904, 60.26805194629116, 59.72483982293292, 58.97176899063085, 53.87504530519224, 49.54731216050337, 50.44141952174457, 51.630991896151734, 51.587259814584144, 53.873724734167844, 55.070498854747456, 55.27746165636038, 55.24410217522042, 55.122663810518766, 55.40649815428828, 56.039078276679305]

In [3]:
x,y = [], []
for i in range(len(injectedDatas)-12):
    x.append(injectedDatas[i:i+12])
    y.append(injectedDatas[i+12])

x, y = array(x), array(y)

cut = 0.75
cut_number = int(cut * len(x))

x_train = x[:cut_number]
y_train = y[:cut_number]

x_test = x[cut_number:]
y_test = y[cut_number:]

x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
x = x.reshape((x.shape[0], x_train.shape[1], 1))

model = Sequential()
model.add(LSTM(20, activation = 'relu', input_shape=(12,1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')
model.summary()

early_stop = EarlyStopping(monitor='loss', patience=1, verbose=1)

model.fit(x_train, y_train, epochs=100, batch_size=1, callbacks=[early_stop])

yhat = model.predict(x[-1:])



print(x[-1:])
print(yhat)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 20)                1760      
_________________________________________________________________
dense (Dense)                (None, 1)                 21        
Total params: 1,781
Trainable params: 1,781
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmprphal1ag.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmprphal1ag.py, lin

In [66]:
answerList = []

nextArray = x[-1:].copy()

for i in range(12):
    ytest = model.predict(nextArray)
    nextArray = np.append(np.delete(nextArray[0], 0), ytest).reshape(1,12,1)
    print(nextArray)
    answerList.append(nextArray[0][-1][0])

[[[53.87504531]
  [49.54731216]
  [50.44141952]
  [51.6309919 ]
  [51.58725981]
  [53.87372473]
  [55.07049885]
  [55.27746166]
  [55.24410218]
  [55.12266381]
  [55.40649815]
  [55.56731415]]]
[[[49.54731216]
  [50.44141952]
  [51.6309919 ]
  [51.58725981]
  [53.87372473]
  [55.07049885]
  [55.27746166]
  [55.24410218]
  [55.12266381]
  [55.40649815]
  [55.56731415]
  [56.13080215]]]
[[[50.44141952]
  [51.6309919 ]
  [51.58725981]
  [53.87372473]
  [55.07049885]
  [55.27746166]
  [55.24410218]
  [55.12266381]
  [55.40649815]
  [55.56731415]
  [56.13080215]
  [56.80785751]]]
[[[51.6309919 ]
  [51.58725981]
  [53.87372473]
  [55.07049885]
  [55.27746166]
  [55.24410218]
  [55.12266381]
  [55.40649815]
  [55.56731415]
  [56.13080215]
  [56.80785751]
  [57.80864716]]]
[[[51.58725981]
  [53.87372473]
  [55.07049885]
  [55.27746166]
  [55.24410218]
  [55.12266381]
  [55.40649815]
  [55.56731415]
  [56.13080215]
  [56.80785751]
  [57.80864716]
  [58.89928436]]]
[[[53.87372473]
  [55.07049885

In [67]:
answerList

[55.56731414794922,
 56.130802154541016,
 56.807857513427734,
 57.80864715576172,
 58.89928436279297,
 60.07240295410156,
 61.106876373291016,
 61.88914489746094,
 62.16657638549805,
 61.706947326660156,
 60.281822204589844,
 58.11912536621094]